apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iu6tdyawo-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c28cf31e31.b5uv.p3.openshiftapps.com/rhtap/rhtap-qe:a21c03df0c3c77b9ab3e8a28da0e5c7c62a2a7d8@sha256:c16b789b46d785bb65308411caa5d5d118fa07d8bfdfe5b877b376d6c9d6e0ad
          name: container-image
